version: '3'
services:
  mariadb:
    build: requirements/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - /home/mkhabou/data/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password1
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password2
      - MYSQL_DATABASE=database
    restart: always
  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress/
    ports:
      - "9000:80"
    volumes:
      - /home/mkhabou/data/wordpress
  nginx:
    build: requirements/nginx/

