version: '3'
services:
#  mariadb:
#    build: requirements/mariadb/
#    ports:
#      - "3306:3306"
#    volumes:
#      - /home/mkhabou/data/mariadb
#    environment:
#      - MYSQL_ROOT_PASSWORD=password1
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password2
#      - MYSQL_DATABASE=database
#    restart: always
  wordpress:
#    depends_on:
#      - mariadb
    build: ./requirements/wordpress/
    ports:
      - "9000:9000"
    volumes:
      - /home/mkhabou/data/wordpress:/var/www/localhost/htdocs
    networks:
      - inception
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - inception

volumes:
  wordpress:

networks:
  inception:
    driver: bridge