version: '3'

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
#    ports:
#      - "3306:3306"
    volumes:
      - mdb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    #ports:
    #  - "9000:9000"
    volumes:
      - wp_data:/var/www/localhost/htdocs
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/localhost/htdocs
    networks:
      - inception
    restart: always


volumes:
  wp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mkhabou/data/wordpress

  mdb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mkhabou/data/mariadb

networks:
  inception:
    driver: bridge